// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bcewsfyhthjcbrtbejky.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJjZXdzZnlodGhqY2JydGJlamt5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA0Njc3MzEsImV4cCI6MjA3NjA0MzczMX0.SArJbTbPzyjeHAIHllTDtTtg7ye3YvCF1xW2ZvWg7Q0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});